-- ============================================================================
-- PortfolioPulse — Stock Catalog Seed Data
-- ============================================================================
-- Populates the `stock_catalog` table with 281 well-known symbols:
--   • S&P 500 / Nasdaq 100 leaders (231 US stocks across all 11 GICS sectors)
--   • Nifty 50 leaders (50 NSE-listed Indian stocks, .NS suffix)
--
-- This table powers the searchable Stock Selector in the Buy/Sell modal:
--   GET /api/stocks/catalog          -> full active list
--   GET /api/stocks/catalog/search   -> autocomplete (symbol or company name)
--   GET /api/stocks/catalog/{symbol} -> catalog metadata + live Yahoo quote
--
-- NOTE on market_cap: values are approximate snapshots taken at seed-creation
-- time, for display/sorting only. They are NOT updated automatically — live
-- prices, sectors for OWNED holdings, and day-change % always come from
-- Yahoo Finance at runtime via YahooFinanceService. NSE market caps are
-- expressed in INR crores-equivalent magnitude for relative ordering only.
--
-- HOW TO RUN:
--   mysql -u root -p portfoliopulse < seed-stock-catalog.sql
--
-- Safe to re-run: `symbol` is UNIQUE, so re-running will fail on duplicate
-- keys. To refresh, first run:
--   TRUNCATE TABLE stock_catalog;
-- ============================================================================

-- US stocks: 231
-- NSE (Nifty 50) stocks: 50
-- TOTAL: 281
-- No duplicate symbols

INSERT INTO stock_catalog (symbol, company_name, sector, industry, exchange, market_cap, is_active) VALUES
('AAPL', 'Apple Inc.', 'Technology', 'Consumer Electronics', 'NASDAQ', 3400.00, TRUE),
('MSFT', 'Microsoft Corporation', 'Technology', 'Software - Infrastructure', 'NASDAQ', 3100.00, TRUE),
('NVDA', 'NVIDIA Corporation', 'Technology', 'Semiconductors', 'NASDAQ', 3000.00, TRUE),
('AVGO', 'Broadcom Inc.', 'Technology', 'Semiconductors', 'NASDAQ', 800.00, TRUE),
('ORCL', 'Oracle Corporation', 'Technology', 'Software - Infrastructure', 'NYSE', 450.00, TRUE),
('CRM', 'Salesforce, Inc.', 'Technology', 'Software - Application', 'NYSE', 300.00, TRUE),
('ADBE', 'Adobe Inc.', 'Technology', 'Software - Application', 'NASDAQ', 250.00, TRUE),
('AMD', 'Advanced Micro Devices, Inc.', 'Technology', 'Semiconductors', 'NASDAQ', 230.00, TRUE),
('CSCO', 'Cisco Systems, Inc.', 'Technology', 'Communication Equipment', 'NASDAQ', 230.00, TRUE),
('ACN', 'Accenture plc', 'Technology', 'Information Technology Services', 'NYSE', 200.00, TRUE),
('IBM', 'International Business Machines Corporation', 'Technology', 'Information Technology Services', 'NYSE', 190.00, TRUE),
('INTC', 'Intel Corporation', 'Technology', 'Semiconductors', 'NASDAQ', 180.00, TRUE),
('TXN', 'Texas Instruments Incorporated', 'Technology', 'Semiconductors', 'NASDAQ', 170.00, TRUE),
('QCOM', 'QUALCOMM Incorporated', 'Technology', 'Semiconductors', 'NASDAQ', 165.00, TRUE),
('NOW', 'ServiceNow, Inc.', 'Technology', 'Software - Application', 'NYSE', 160.00, TRUE),
('INTU', 'Intuit Inc.', 'Technology', 'Software - Application', 'NASDAQ', 160.00, TRUE),
('AMAT', 'Applied Materials, Inc.', 'Technology', 'Semiconductor Equipment & Materials', 'NASDAQ', 140.00, TRUE),
('ADI', 'Analog Devices, Inc.', 'Technology', 'Semiconductors', 'NASDAQ', 100.00, TRUE),
('LRCX', 'Lam Research Corporation', 'Technology', 'Semiconductor Equipment & Materials', 'NASDAQ', 110.00, TRUE),
('MU', 'Micron Technology, Inc.', 'Technology', 'Semiconductors', 'NASDAQ', 120.00, TRUE),
('PANW', 'Palo Alto Networks, Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 110.00, TRUE),
('KLAC', 'KLA Corporation', 'Technology', 'Semiconductor Equipment & Materials', 'NASDAQ', 100.00, TRUE),
('SNPS', 'Synopsys, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 80.00, TRUE),
('CDNS', 'Cadence Design Systems, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 85.00, TRUE),
('ADSK', 'Autodesk, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 55.00, TRUE),
('ROP', 'Roper Technologies, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 60.00, TRUE),
('FTNT', 'Fortinet, Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 70.00, TRUE),
('MSI', 'Motorola Solutions, Inc.', 'Technology', 'Communication Equipment', 'NYSE', 65.00, TRUE),
('APH', 'Amphenol Corporation', 'Technology', 'Electronic Components', 'NYSE', 100.00, TRUE),
('HPQ', 'HP Inc.', 'Technology', 'Computer Hardware', 'NYSE', 35.00, TRUE),
('DELL', 'Dell Technologies Inc.', 'Technology', 'Computer Hardware', 'NYSE', 80.00, TRUE),
('NXPI', 'NXP Semiconductors N.V.', 'Technology', 'Semiconductors', 'NASDAQ', 55.00, TRUE),
('MCHP', 'Microchip Technology Incorporated', 'Technology', 'Semiconductors', 'NASDAQ', 35.00, TRUE),
('WDAY', 'Workday, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 65.00, TRUE),
('PLTR', 'Palantir Technologies Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 250.00, TRUE),
('UBER', 'Uber Technologies, Inc.', 'Technology', 'Software - Application', 'NYSE', 150.00, TRUE),
('SHOP', 'Shopify Inc.', 'Technology', 'Software - Application', 'NYSE', 120.00, TRUE),
('TEAM', 'Atlassian Corporation', 'Technology', 'Software - Application', 'NASDAQ', 50.00, TRUE),
('DDOG', 'Datadog, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 40.00, TRUE),
('ZS', 'Zscaler, Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 30.00, TRUE),
('CRWD', 'CrowdStrike Holdings, Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 90.00, TRUE),
('PYPL', 'PayPal Holdings, Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 70.00, TRUE),
('SQ', 'Block, Inc.', 'Technology', 'Software - Infrastructure', 'NYSE', 45.00, TRUE),
('MRVL', 'Marvell Technology, Inc.', 'Technology', 'Semiconductors', 'NASDAQ', 65.00, TRUE),
('ON', 'ON Semiconductor Corporation', 'Technology', 'Semiconductors', 'NASDAQ', 25.00, TRUE),
('GLW', 'Corning Incorporated', 'Technology', 'Electronic Components', 'NYSE', 40.00, TRUE),
('KEYS', 'Keysight Technologies, Inc.', 'Technology', 'Scientific & Technical Instruments', 'NYSE', 30.00, TRUE),
('ANSS', 'ANSYS, Inc.', 'Technology', 'Software - Application', 'NASDAQ', 35.00, TRUE),
('FICO', 'Fair Isaac Corporation', 'Technology', 'Software - Application', 'NYSE', 45.00, TRUE),
('GEN', 'Gen Digital Inc.', 'Technology', 'Software - Infrastructure', 'NASDAQ', 18.00, TRUE),
('CTSH', 'Cognizant Technology Solutions Corporation', 'Technology', 'Information Technology Services', 'NASDAQ', 38.00, TRUE),
('GOOGL', 'Alphabet Inc. Class A', 'Communication Services', 'Internet Content & Information', 'NASDAQ', 2200.00, TRUE),
('GOOG', 'Alphabet Inc. Class C', 'Communication Services', 'Internet Content & Information', 'NASDAQ', 2200.00, TRUE),
('META', 'Meta Platforms, Inc.', 'Communication Services', 'Internet Content & Information', 'NASDAQ', 1500.00, TRUE),
('NFLX', 'Netflix, Inc.', 'Communication Services', 'Entertainment', 'NASDAQ', 350.00, TRUE),
('DIS', 'The Walt Disney Company', 'Communication Services', 'Entertainment', 'NYSE', 200.00, TRUE),
('CMCSA', 'Comcast Corporation', 'Communication Services', 'Telecom Services', 'NASDAQ', 150.00, TRUE),
('T', 'AT&T Inc.', 'Communication Services', 'Telecom Services', 'NYSE', 170.00, TRUE),
('VZ', 'Verizon Communications Inc.', 'Communication Services', 'Telecom Services', 'NYSE', 180.00, TRUE),
('TMUS', 'T-Mobile US, Inc.', 'Communication Services', 'Telecom Services', 'NASDAQ', 230.00, TRUE),
('EA', 'Electronic Arts Inc.', 'Communication Services', 'Electronic Gaming & Multimedia', 'NASDAQ', 40.00, TRUE),
('TTWO', 'Take-Two Interactive Software, Inc.', 'Communication Services', 'Electronic Gaming & Multimedia', 'NASDAQ', 30.00, TRUE),
('WBD', 'Warner Bros. Discovery, Inc.', 'Communication Services', 'Entertainment', 'NASDAQ', 25.00, TRUE),
('CHTR', 'Charter Communications, Inc.', 'Communication Services', 'Telecom Services', 'NASDAQ', 45.00, TRUE),
('MTCH', 'Match Group, Inc.', 'Communication Services', 'Internet Content & Information', 'NASDAQ', 8.00, TRUE),
('PINS', 'Pinterest, Inc.', 'Communication Services', 'Internet Content & Information', 'NYSE', 22.00, TRUE),
('SNAP', 'Snap Inc.', 'Communication Services', 'Internet Content & Information', 'NYSE', 15.00, TRUE),
('SPOT', 'Spotify Technology S.A.', 'Communication Services', 'Internet Content & Information', 'NYSE', 100.00, TRUE),
('ROKU', 'Roku, Inc.', 'Communication Services', 'Entertainment', 'NASDAQ', 8.00, TRUE),
('LYV', 'Live Nation Entertainment, Inc.', 'Communication Services', 'Entertainment', 'NYSE', 28.00, TRUE),
('AMZN', 'Amazon.com, Inc.', 'Consumer Cyclical', 'Internet Retail', 'NASDAQ', 2000.00, TRUE),
('TSLA', 'Tesla, Inc.', 'Consumer Cyclical', 'Auto Manufacturers', 'NASDAQ', 1000.00, TRUE),
('HD', 'The Home Depot, Inc.', 'Consumer Cyclical', 'Home Improvement Retail', 'NYSE', 400.00, TRUE),
('MCD', 'McDonald\'s Corporation', 'Consumer Cyclical', 'Restaurants', 'NYSE', 220.00, TRUE),
('BKNG', 'Booking Holdings Inc.', 'Consumer Cyclical', 'Travel Services', 'NASDAQ', 160.00, TRUE),
('TJX', 'The TJX Companies, Inc.', 'Consumer Cyclical', 'Apparel Retail', 'NYSE', 140.00, TRUE),
('NKE', 'NIKE, Inc.', 'Consumer Cyclical', 'Footwear & Accessories', 'NYSE', 100.00, TRUE),
('LOW', 'Lowe\'s Companies, Inc.', 'Consumer Cyclical', 'Home Improvement Retail', 'NYSE', 150.00, TRUE),
('SBUX', 'Starbucks Corporation', 'Consumer Cyclical', 'Restaurants', 'NASDAQ', 110.00, TRUE),
('ABNB', 'Airbnb, Inc.', 'Consumer Cyclical', 'Travel Services', 'NASDAQ', 80.00, TRUE),
('CMG', 'Chipotle Mexican Grill, Inc.', 'Consumer Cyclical', 'Restaurants', 'NYSE', 80.00, TRUE),
('MAR', 'Marriott International, Inc.', 'Consumer Cyclical', 'Lodging', 'NASDAQ', 75.00, TRUE),
('GM', 'General Motors Company', 'Consumer Cyclical', 'Auto Manufacturers', 'NYSE', 55.00, TRUE),
('F', 'Ford Motor Company', 'Consumer Cyclical', 'Auto Manufacturers', 'NYSE', 45.00, TRUE),
('ORLY', 'O\'Reilly Automotive, Inc.', 'Consumer Cyclical', 'Specialty Retail', 'NASDAQ', 75.00, TRUE),
('AZO', 'AutoZone, Inc.', 'Consumer Cyclical', 'Specialty Retail', 'NYSE', 60.00, TRUE),
('ROST', 'Ross Stores, Inc.', 'Consumer Cyclical', 'Apparel Retail', 'NASDAQ', 50.00, TRUE),
('YUM', 'Yum! Brands, Inc.', 'Consumer Cyclical', 'Restaurants', 'NYSE', 38.00, TRUE),
('HLT', 'Hilton Worldwide Holdings Inc.', 'Consumer Cyclical', 'Lodging', 'NYSE', 60.00, TRUE),
('EXPE', 'Expedia Group, Inc.', 'Consumer Cyclical', 'Travel Services', 'NASDAQ', 22.00, TRUE),
('DPZ', 'Domino\'s Pizza, Inc.', 'Consumer Cyclical', 'Restaurants', 'NYSE', 16.00, TRUE),
('DHI', 'D.R. Horton, Inc.', 'Consumer Cyclical', 'Residential Construction', 'NYSE', 45.00, TRUE),
('LEN', 'Lennar Corporation', 'Consumer Cyclical', 'Residential Construction', 'NYSE', 35.00, TRUE),
('RCL', 'Royal Caribbean Cruises Ltd.', 'Consumer Cyclical', 'Travel Services', 'NYSE', 60.00, TRUE),
('CCL', 'Carnival Corporation & plc', 'Consumer Cyclical', 'Travel Services', 'NYSE', 35.00, TRUE),
('BRK.B', 'Berkshire Hathaway Inc.', 'Financial Services', 'Insurance - Diversified', 'NYSE', 950.00, TRUE),
('JPM', 'JPMorgan Chase & Co.', 'Financial Services', 'Banks - Diversified', 'NYSE', 700.00, TRUE),
('V', 'Visa Inc.', 'Financial Services', 'Credit Services', 'NYSE', 550.00, TRUE),
('MA', 'Mastercard Incorporated', 'Financial Services', 'Credit Services', 'NYSE', 450.00, TRUE),
('BAC', 'Bank of America Corporation', 'Financial Services', 'Banks - Diversified', 'NYSE', 320.00, TRUE),
('WFC', 'Wells Fargo & Company', 'Financial Services', 'Banks - Diversified', 'NYSE', 230.00, TRUE),
('GS', 'The Goldman Sachs Group, Inc.', 'Financial Services', 'Capital Markets', 'NYSE', 180.00, TRUE),
('MS', 'Morgan Stanley', 'Financial Services', 'Capital Markets', 'NYSE', 170.00, TRUE),
('SCHW', 'The Charles Schwab Corporation', 'Financial Services', 'Capital Markets', 'NYSE', 140.00, TRUE),
('AXP', 'American Express Company', 'Financial Services', 'Credit Services', 'NYSE', 200.00, TRUE),
('BLK', 'BlackRock, Inc.', 'Financial Services', 'Asset Management', 'NYSE', 150.00, TRUE),
('C', 'Citigroup Inc.', 'Financial Services', 'Banks - Diversified', 'NYSE', 140.00, TRUE),
('SPGI', 'S&P Global Inc.', 'Financial Services', 'Financial Data & Stock Exchanges', 'NYSE', 150.00, TRUE),
('PGR', 'The Progressive Corporation', 'Financial Services', 'Insurance - Property & Casualty', 'NYSE', 150.00, TRUE),
('CB', 'Chubb Limited', 'Financial Services', 'Insurance - Property & Casualty', 'NYSE', 110.00, TRUE),
('PNC', 'The PNC Financial Services Group, Inc.', 'Financial Services', 'Banks - Regional', 'NYSE', 75.00, TRUE),
('USB', 'U.S. Bancorp', 'Financial Services', 'Banks - Regional', 'NYSE', 75.00, TRUE),
('TFC', 'Truist Financial Corporation', 'Financial Services', 'Banks - Regional', 'NYSE', 55.00, TRUE),
('ICE', 'Intercontinental Exchange, Inc.', 'Financial Services', 'Financial Data & Stock Exchanges', 'NYSE', 95.00, TRUE),
('CME', 'CME Group Inc.', 'Financial Services', 'Financial Data & Stock Exchanges', 'NASDAQ', 85.00, TRUE),
('MMC', 'Marsh & McLennan Companies, Inc.', 'Financial Services', 'Insurance Brokers', 'NYSE', 110.00, TRUE),
('AON', 'Aon plc', 'Financial Services', 'Insurance Brokers', 'NYSE', 75.00, TRUE),
('AIG', 'American International Group, Inc.', 'Financial Services', 'Insurance - Diversified', 'NYSE', 50.00, TRUE),
('MET', 'MetLife, Inc.', 'Financial Services', 'Insurance - Life', 'NYSE', 55.00, TRUE),
('PRU', 'Prudential Financial, Inc.', 'Financial Services', 'Insurance - Life', 'NYSE', 40.00, TRUE),
('COF', 'Capital One Financial Corporation', 'Financial Services', 'Credit Services', 'NYSE', 70.00, TRUE),
('FI', 'Fiserv, Inc.', 'Financial Services', 'Information Technology Services', 'NYSE', 90.00, TRUE),
('LLY', 'Eli Lilly and Company', 'Healthcare', 'Drug Manufacturers - General', 'NYSE', 750.00, TRUE),
('UNH', 'UnitedHealth Group Incorporated', 'Healthcare', 'Healthcare Plans', 'NYSE', 450.00, TRUE),
('JNJ', 'Johnson & Johnson', 'Healthcare', 'Drug Manufacturers - General', 'NYSE', 380.00, TRUE),
('ABBV', 'AbbVie Inc.', 'Healthcare', 'Drug Manufacturers - General', 'NYSE', 340.00, TRUE),
('MRK', 'Merck & Co., Inc.', 'Healthcare', 'Drug Manufacturers - General', 'NYSE', 260.00, TRUE),
('ABT', 'Abbott Laboratories', 'Healthcare', 'Medical Devices', 'NYSE', 200.00, TRUE),
('TMO', 'Thermo Fisher Scientific Inc.', 'Healthcare', 'Diagnostics & Research', 'NYSE', 190.00, TRUE),
('PFE', 'Pfizer Inc.', 'Healthcare', 'Drug Manufacturers - General', 'NYSE', 160.00, TRUE),
('DHR', 'Danaher Corporation', 'Healthcare', 'Diagnostics & Research', 'NYSE', 170.00, TRUE),
('ISRG', 'Intuitive Surgical, Inc.', 'Healthcare', 'Medical Instruments & Supplies', 'NASDAQ', 190.00, TRUE),
('AMGN', 'Amgen Inc.', 'Healthcare', 'Drug Manufacturers - General', 'NASDAQ', 160.00, TRUE),
('SYK', 'Stryker Corporation', 'Healthcare', 'Medical Devices', 'NYSE', 150.00, TRUE),
('BSX', 'Boston Scientific Corporation', 'Healthcare', 'Medical Devices', 'NYSE', 130.00, TRUE),
('MDT', 'Medtronic plc', 'Healthcare', 'Medical Devices', 'NYSE', 110.00, TRUE),
('VRTX', 'Vertex Pharmaceuticals Incorporated', 'Healthcare', 'Biotechnology', 'NASDAQ', 120.00, TRUE),
('GILD', 'Gilead Sciences, Inc.', 'Healthcare', 'Drug Manufacturers - General', 'NASDAQ', 100.00, TRUE),
('REGN', 'Regeneron Pharmaceuticals, Inc.', 'Healthcare', 'Biotechnology', 'NASDAQ', 90.00, TRUE),
('CI', 'The Cigna Group', 'Healthcare', 'Healthcare Plans', 'NYSE', 90.00, TRUE),
('ELV', 'Elevance Health, Inc.', 'Healthcare', 'Healthcare Plans', 'NYSE', 90.00, TRUE),
('CVS', 'CVS Health Corporation', 'Healthcare', 'Healthcare Plans', 'NYSE', 75.00, TRUE),
('ZTS', 'Zoetis Inc.', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 'NYSE', 80.00, TRUE),
('HCA', 'HCA Healthcare, Inc.', 'Healthcare', 'Medical Care Facilities', 'NYSE', 95.00, TRUE),
('BDX', 'Becton, Dickinson and Company', 'Healthcare', 'Medical Instruments & Supplies', 'NYSE', 65.00, TRUE),
('MRNA', 'Moderna, Inc.', 'Healthcare', 'Biotechnology', 'NASDAQ', 30.00, TRUE),
('BIIB', 'Biogen Inc.', 'Healthcare', 'Biotechnology', 'NASDAQ', 18.00, TRUE),
('EW', 'Edwards Lifesciences Corporation', 'Healthcare', 'Medical Devices', 'NYSE', 40.00, TRUE),
('WMT', 'Walmart Inc.', 'Consumer Defensive', 'Discount Stores', 'NYSE', 700.00, TRUE),
('COST', 'Costco Wholesale Corporation', 'Consumer Defensive', 'Discount Stores', 'NASDAQ', 400.00, TRUE),
('PG', 'The Procter & Gamble Company', 'Consumer Defensive', 'Household & Personal Products', 'NYSE', 400.00, TRUE),
('KO', 'The Coca-Cola Company', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 'NYSE', 290.00, TRUE),
('PEP', 'PepsiCo, Inc.', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 'NASDAQ', 220.00, TRUE),
('PM', 'Philip Morris International Inc.', 'Consumer Defensive', 'Tobacco', 'NYSE', 220.00, TRUE),
('MO', 'Altria Group, Inc.', 'Consumer Defensive', 'Tobacco', 'NYSE', 95.00, TRUE),
('MDLZ', 'Mondelez International, Inc.', 'Consumer Defensive', 'Confectioners', 'NASDAQ', 90.00, TRUE),
('CL', 'Colgate-Palmolive Company', 'Consumer Defensive', 'Household & Personal Products', 'NYSE', 80.00, TRUE),
('TGT', 'Target Corporation', 'Consumer Defensive', 'Discount Stores', 'NYSE', 70.00, TRUE),
('KMB', 'Kimberly-Clark Corporation', 'Consumer Defensive', 'Household & Personal Products', 'NYSE', 48.00, TRUE),
('GIS', 'General Mills, Inc.', 'Consumer Defensive', 'Packaged Foods', 'NYSE', 35.00, TRUE),
('KHC', 'The Kraft Heinz Company', 'Consumer Defensive', 'Packaged Foods', 'NASDAQ', 38.00, TRUE),
('STZ', 'Constellation Brands, Inc.', 'Consumer Defensive', 'Beverages - Wineries & Distilleries', 'NYSE', 35.00, TRUE),
('KDP', 'Keurig Dr Pepper Inc.', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 'NASDAQ', 45.00, TRUE),
('SYY', 'Sysco Corporation', 'Consumer Defensive', 'Food Distribution', 'NYSE', 40.00, TRUE),
('KR', 'The Kroger Co.', 'Consumer Defensive', 'Grocery Stores', 'NYSE', 40.00, TRUE),
('DG', 'Dollar General Corporation', 'Consumer Defensive', 'Discount Stores', 'NYSE', 18.00, TRUE),
('EL', 'The Estée Lauder Companies Inc.', 'Consumer Defensive', 'Household & Personal Products', 'NYSE', 25.00, TRUE),
('GE', 'GE Aerospace', 'Industrials', 'Aerospace & Defense', 'NYSE', 220.00, TRUE),
('CAT', 'Caterpillar Inc.', 'Industrials', 'Farm & Heavy Construction Machinery', 'NYSE', 190.00, TRUE),
('RTX', 'RTX Corporation', 'Industrials', 'Aerospace & Defense', 'NYSE', 180.00, TRUE),
('HON', 'Honeywell International Inc.', 'Industrials', 'Conglomerates', 'NASDAQ', 140.00, TRUE),
('UNP', 'Union Pacific Corporation', 'Industrials', 'Railroads', 'NYSE', 150.00, TRUE),
('BA', 'The Boeing Company', 'Industrials', 'Aerospace & Defense', 'NYSE', 110.00, TRUE),
('UPS', 'United Parcel Service, Inc.', 'Industrials', 'Integrated Freight & Logistics', 'NYSE', 110.00, TRUE),
('LMT', 'Lockheed Martin Corporation', 'Industrials', 'Aerospace & Defense', 'NYSE', 110.00, TRUE),
('DE', 'Deere & Company', 'Industrials', 'Farm & Heavy Construction Machinery', 'NYSE', 120.00, TRUE),
('ETN', 'Eaton Corporation plc', 'Industrials', 'Specialty Industrial Machinery', 'NYSE', 130.00, TRUE),
('ADP', 'Automatic Data Processing, Inc.', 'Industrials', 'Staffing & Employment Services', 'NASDAQ', 115.00, TRUE),
('NOC', 'Northrop Grumman Corporation', 'Industrials', 'Aerospace & Defense', 'NYSE', 75.00, TRUE),
('GD', 'General Dynamics Corporation', 'Industrials', 'Aerospace & Defense', 'NYSE', 80.00, TRUE),
('ITW', 'Illinois Tool Works Inc.', 'Industrials', 'Specialty Industrial Machinery', 'NYSE', 75.00, TRUE),
('MMM', '3M Company', 'Industrials', 'Conglomerates', 'NYSE', 80.00, TRUE),
('CSX', 'CSX Corporation', 'Industrials', 'Railroads', 'NASDAQ', 65.00, TRUE),
('NSC', 'Norfolk Southern Corporation', 'Industrials', 'Railroads', 'NYSE', 60.00, TRUE),
('FDX', 'FedEx Corporation', 'Industrials', 'Integrated Freight & Logistics', 'NYSE', 65.00, TRUE),
('EMR', 'Emerson Electric Co.', 'Industrials', 'Specialty Industrial Machinery', 'NYSE', 70.00, TRUE),
('PH', 'Parker-Hannifin Corporation', 'Industrials', 'Specialty Industrial Machinery', 'NYSE', 90.00, TRUE),
('TT', 'Trane Technologies plc', 'Industrials', 'Building Products & Equipment', 'NYSE', 90.00, TRUE),
('CARR', 'Carrier Global Corporation', 'Industrials', 'Building Products & Equipment', 'NYSE', 60.00, TRUE),
('WM', 'Waste Management, Inc.', 'Industrials', 'Waste Management', 'NYSE', 85.00, TRUE),
('PCAR', 'PACCAR Inc', 'Industrials', 'Farm & Heavy Construction Machinery', 'NASDAQ', 55.00, TRUE),
('URI', 'United Rentals, Inc.', 'Industrials', 'Rental & Leasing Services', 'NYSE', 50.00, TRUE),
('XOM', 'Exxon Mobil Corporation', 'Energy', 'Oil & Gas Integrated', 'NYSE', 480.00, TRUE),
('CVX', 'Chevron Corporation', 'Energy', 'Oil & Gas Integrated', 'NYSE', 270.00, TRUE),
('COP', 'ConocoPhillips', 'Energy', 'Oil & Gas E&P', 'NYSE', 120.00, TRUE),
('SLB', 'Schlumberger Limited', 'Energy', 'Oil & Gas Equipment & Services', 'NYSE', 55.00, TRUE),
('EOG', 'EOG Resources, Inc.', 'Energy', 'Oil & Gas E&P', 'NYSE', 70.00, TRUE),
('MPC', 'Marathon Petroleum Corporation', 'Energy', 'Oil & Gas Refining & Marketing', 'NYSE', 55.00, TRUE),
('PSX', 'Phillips 66', 'Energy', 'Oil & Gas Refining & Marketing', 'NYSE', 50.00, TRUE),
('WMB', 'The Williams Companies, Inc.', 'Energy', 'Oil & Gas Midstream', 'NYSE', 65.00, TRUE),
('OXY', 'Occidental Petroleum Corporation', 'Energy', 'Oil & Gas E&P', 'NYSE', 45.00, TRUE),
('KMI', 'Kinder Morgan, Inc.', 'Energy', 'Oil & Gas Midstream', 'NYSE', 60.00, TRUE),
('VLO', 'Valero Energy Corporation', 'Energy', 'Oil & Gas Refining & Marketing', 'NYSE', 45.00, TRUE),
('NEE', 'NextEra Energy, Inc.', 'Utilities', 'Utilities - Regulated Electric', 'NYSE', 150.00, TRUE),
('SO', 'The Southern Company', 'Utilities', 'Utilities - Regulated Electric', 'NYSE', 95.00, TRUE),
('DUK', 'Duke Energy Corporation', 'Utilities', 'Utilities - Regulated Electric', 'NYSE', 90.00, TRUE),
('CEG', 'Constellation Energy Corporation', 'Utilities', 'Utilities - Renewable', 'NASDAQ', 85.00, TRUE),
('AEP', 'American Electric Power Company, Inc.', 'Utilities', 'Utilities - Regulated Electric', 'NASDAQ', 55.00, TRUE),
('D', 'Dominion Energy, Inc.', 'Utilities', 'Utilities - Regulated Electric', 'NYSE', 50.00, TRUE),
('EXC', 'Exelon Corporation', 'Utilities', 'Utilities - Regulated Electric', 'NASDAQ', 45.00, TRUE),
('PEG', 'Public Service Enterprise Group Incorporated', 'Utilities', 'Utilities - Regulated Electric', 'NYSE', 45.00, TRUE),
('XEL', 'Xcel Energy Inc.', 'Utilities', 'Utilities - Regulated Electric', 'NASDAQ', 38.00, TRUE),
('ED', 'Consolidated Edison, Inc.', 'Utilities', 'Utilities - Regulated Electric', 'NYSE', 35.00, TRUE),
('PLD', 'Prologis, Inc.', 'Real Estate', 'REIT - Industrial', 'NYSE', 100.00, TRUE),
('AMT', 'American Tower Corporation', 'Real Estate', 'REIT - Specialty', 'NYSE', 90.00, TRUE),
('EQIX', 'Equinix, Inc.', 'Real Estate', 'REIT - Specialty', 'NASDAQ', 80.00, TRUE),
('WELL', 'Welltower Inc.', 'Real Estate', 'REIT - Healthcare Facilities', 'NYSE', 85.00, TRUE),
('DLR', 'Digital Realty Trust, Inc.', 'Real Estate', 'REIT - Specialty', 'NYSE', 60.00, TRUE),
('SPG', 'Simon Property Group, Inc.', 'Real Estate', 'REIT - Retail', 'NYSE', 60.00, TRUE),
('O', 'Realty Income Corporation', 'Real Estate', 'REIT - Retail', 'NYSE', 50.00, TRUE),
('PSA', 'Public Storage', 'Real Estate', 'REIT - Industrial', 'NYSE', 55.00, TRUE),
('CCI', 'Crown Castle Inc.', 'Real Estate', 'REIT - Specialty', 'NYSE', 45.00, TRUE),
('VICI', 'VICI Properties Inc.', 'Real Estate', 'REIT - Diversified', 'NYSE', 33.00, TRUE),
('LIN', 'Linde plc', 'Basic Materials', 'Specialty Chemicals', 'NASDAQ', 220.00, TRUE),
('APD', 'Air Products and Chemicals, Inc.', 'Basic Materials', 'Specialty Chemicals', 'NYSE', 65.00, TRUE),
('SHW', 'The Sherwin-Williams Company', 'Basic Materials', 'Specialty Chemicals', 'NYSE', 90.00, TRUE),
('FCX', 'Freeport-McMoRan Inc.', 'Basic Materials', 'Copper', 'NYSE', 60.00, TRUE),
('NEM', 'Newmont Corporation', 'Basic Materials', 'Gold', 'NYSE', 55.00, TRUE),
('ECL', 'Ecolab Inc.', 'Basic Materials', 'Specialty Chemicals', 'NYSE', 75.00, TRUE),
('NUE', 'Nucor Corporation', 'Basic Materials', 'Steel', 'NYSE', 35.00, TRUE),
('DOW', 'Dow Inc.', 'Basic Materials', 'Chemicals', 'NYSE', 28.00, TRUE),
('RELIANCE.NS', 'Reliance Industries Limited', 'Energy', 'Oil & Gas Refining & Marketing', 'NSE', 1500000.00, TRUE),
('TCS.NS', 'Tata Consultancy Services Limited', 'Technology', 'Information Technology Services', 'NSE', 1300000.00, TRUE),
('HDFCBANK.NS', 'HDFC Bank Limited', 'Financial Services', 'Banks - Regional', 'NSE', 1100000.00, TRUE),
('ICICIBANK.NS', 'ICICI Bank Limited', 'Financial Services', 'Banks - Regional', 'NSE', 800000.00, TRUE),
('BHARTIARTL.NS', 'Bharti Airtel Limited', 'Communication Services', 'Telecom Services', 'NSE', 700000.00, TRUE),
('INFY.NS', 'Infosys Limited', 'Technology', 'Information Technology Services', 'NSE', 650000.00, TRUE),
('SBIN.NS', 'State Bank of India', 'Financial Services', 'Banks - Regional', 'NSE', 650000.00, TRUE),
('LICI.NS', 'Life Insurance Corporation of India', 'Financial Services', 'Insurance - Life', 'NSE', 500000.00, TRUE),
('HINDUNILVR.NS', 'Hindustan Unilever Limited', 'Consumer Defensive', 'Household & Personal Products', 'NSE', 550000.00, TRUE),
('ITC.NS', 'ITC Limited', 'Consumer Defensive', 'Tobacco', 'NSE', 530000.00, TRUE),
('LT.NS', 'Larsen & Toubro Limited', 'Industrials', 'Engineering & Construction', 'NSE', 480000.00, TRUE),
('HCLTECH.NS', 'HCL Technologies Limited', 'Technology', 'Information Technology Services', 'NSE', 430000.00, TRUE),
('BAJFINANCE.NS', 'Bajaj Finance Limited', 'Financial Services', 'Credit Services', 'NSE', 430000.00, TRUE),
('MARUTI.NS', 'Maruti Suzuki India Limited', 'Consumer Cyclical', 'Auto Manufacturers', 'NSE', 380000.00, TRUE),
('SUNPHARMA.NS', 'Sun Pharmaceutical Industries Limited', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 'NSE', 400000.00, TRUE),
('KOTAKBANK.NS', 'Kotak Mahindra Bank Limited', 'Financial Services', 'Banks - Regional', 'NSE', 360000.00, TRUE),
('ONGC.NS', 'Oil and Natural Gas Corporation Limited', 'Energy', 'Oil & Gas E&P', 'NSE', 340000.00, TRUE),
('TATAMOTORS.NS', 'Tata Motors Limited', 'Consumer Cyclical', 'Auto Manufacturers', 'NSE', 330000.00, TRUE),
('NTPC.NS', 'NTPC Limited', 'Utilities', 'Utilities - Regulated Electric', 'NSE', 330000.00, TRUE),
('AXISBANK.NS', 'Axis Bank Limited', 'Financial Services', 'Banks - Regional', 'NSE', 330000.00, TRUE),
('ADANIENT.NS', 'Adani Enterprises Limited', 'Industrials', 'Conglomerates', 'NSE', 320000.00, TRUE),
('M&M.NS', 'Mahindra & Mahindra Limited', 'Consumer Cyclical', 'Auto Manufacturers', 'NSE', 320000.00, TRUE),
('ULTRACEMCO.NS', 'UltraTech Cement Limited', 'Basic Materials', 'Building Materials', 'NSE', 300000.00, TRUE),
('HINDALCO.NS', 'Hindalco Industries Limited', 'Basic Materials', 'Aluminum', 'NSE', 230000.00, TRUE),
('ASIANPAINT.NS', 'Asian Paints Limited', 'Basic Materials', 'Specialty Chemicals', 'NSE', 230000.00, TRUE),
('TITAN.NS', 'Titan Company Limited', 'Consumer Cyclical', 'Luxury Goods', 'NSE', 280000.00, TRUE),
('POWERGRID.NS', 'Power Grid Corporation of India Limited', 'Utilities', 'Utilities - Regulated Electric', 'NSE', 270000.00, TRUE),
('BAJAJFINSV.NS', 'Bajaj Finserv Limited', 'Financial Services', 'Insurance - Diversified', 'NSE', 270000.00, TRUE),
('NESTLEIND.NS', 'Nestle India Limited', 'Consumer Defensive', 'Packaged Foods', 'NSE', 230000.00, TRUE),
('WIPRO.NS', 'Wipro Limited', 'Technology', 'Information Technology Services', 'NSE', 250000.00, TRUE),
('JSWSTEEL.NS', 'JSW Steel Limited', 'Basic Materials', 'Steel', 'NSE', 240000.00, TRUE),
('COALINDIA.NS', 'Coal India Limited', 'Energy', 'Thermal Coal', 'NSE', 250000.00, TRUE),
('TATASTEEL.NS', 'Tata Steel Limited', 'Basic Materials', 'Steel', 'NSE', 200000.00, TRUE),
('GRASIM.NS', 'Grasim Industries Limited', 'Basic Materials', 'Chemicals', 'NSE', 170000.00, TRUE),
('TECHM.NS', 'Tech Mahindra Limited', 'Technology', 'Information Technology Services', 'NSE', 160000.00, TRUE),
('SBILIFE.NS', 'SBI Life Insurance Company Limited', 'Financial Services', 'Insurance - Life', 'NSE', 180000.00, TRUE),
('HDFCLIFE.NS', 'HDFC Life Insurance Company Limited', 'Financial Services', 'Insurance - Life', 'NSE', 150000.00, TRUE),
('DRREDDY.NS', 'Dr. Reddy\'s Laboratories Limited', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 'NSE', 120000.00, TRUE),
('CIPLA.NS', 'Cipla Limited', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 'NSE', 120000.00, TRUE),
('EICHERMOT.NS', 'Eicher Motors Limited', 'Consumer Cyclical', 'Auto Manufacturers', 'NSE', 130000.00, TRUE),
('BAJAJ-AUTO.NS', 'Bajaj Auto Limited', 'Consumer Cyclical', 'Auto Manufacturers', 'NSE', 250000.00, TRUE),
('APOLLOHOSP.NS', 'Apollo Hospitals Enterprise Limited', 'Healthcare', 'Medical Care Facilities', 'NSE', 90000.00, TRUE),
('INDUSINDBK.NS', 'IndusInd Bank Limited', 'Financial Services', 'Banks - Regional', 'NSE', 90000.00, TRUE),
('HEROMOTOCO.NS', 'Hero MotoCorp Limited', 'Consumer Cyclical', 'Auto Manufacturers', 'NSE', 100000.00, TRUE),
('BPCL.NS', 'Bharat Petroleum Corporation Limited', 'Energy', 'Oil & Gas Refining & Marketing', 'NSE', 100000.00, TRUE),
('DIVISLAB.NS', 'Divi\'s Laboratories Limited', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 'NSE', 100000.00, TRUE),
('SHRIRAMFIN.NS', 'Shriram Finance Limited', 'Financial Services', 'Credit Services', 'NSE', 100000.00, TRUE),
('TRENT.NS', 'Trent Limited', 'Consumer Cyclical', 'Apparel Retail', 'NSE', 250000.00, TRUE),
('ADANIPORTS.NS', 'Adani Ports and Special Economic Zone Limited', 'Industrials', 'Marine Shipping', 'NSE', 280000.00, TRUE),
('LTIM.NS', 'LTIMindtree Limited', 'Technology', 'Information Technology Services', 'NSE', 170000.00, TRUE);
